import type { View } from "@shared/types";

export const data: View[] = [
  {
    status: "Open",
    id: 1,
    subject: "Hello! lorem ipsum dolor 1",
    petitioner: "Erik Johson",
    requested: "03/28",
    actualization: "04/15",
    group: "Support",
  },
  {
    status: "Closed",
    id: 2,
    subject: "Hello! lorem ipsum dolor 2",
    petitioner: "Erik Johson",
    requested: "03/28",
    actualization: "04/15",
    group: "Development",
  },
  {
    status: "Open",
    id: 3,
    subject: "Hello! lorem ipsum dolor 4",
    petitioner: "Erik Johson",
    requested: "03/28",
    actualization: "04/15",
    group: "Design",
  },
  {
    status: "In review",
    id: 4,
    subject: "Hello! lorem ipsum dolor 4",
    petitioner: "Erik Johson",
    requested: "03/28",
    actualization: "04/15",
    group: "Support",
  },
  {
    status: "Open",
    id: 5,
    subject: "Hello! lorem ipsum dolor 5",
    petitioner: "Erik Johson",
    requested: "03/28",
    actualization: "04/15",
    group: "Support",
  },
  {
    status: "Closed",
    id: 6,
    subject: "Hello! lorem ipsum dolor 6",
    petitioner: "Erik Johson",
    requested: "03/28",
    actualization: "04/15",
    group: "Development",
  },
  {
    status: "Open",
    id: 7,
    subject: "Hello! lorem ipsum dolor 7",
    petitioner: "Erik Johson",
    requested: "03/28",
    actualization: "04/15",
    group: "Design",
  },
];
